### ISSUE TITLE
Poll Konnektive for orders (2-3 days)

### ISSUE THREAD

**Issue by onedanshow** [Woodbolt-International/konnektive_integration#2]
Here is their API endpoint to hit: https://api.konnektive.com/docs/order_query/

We'll need a timestamp so we know the last time that we pull.

**Comment by apeacox** [comment]
we can close this task. I use wombat to poll konnektive API because it hasn't a granular way to poll data based on timestamps.

so, the most sharp way is to poll for a date (yes, entire 24hours of a day). wombat already lets to do this automatically, so we just need to create a proxy between the two services. this was already accomplished with issue #1
